backend:
  name: github
  repo: mohamadali84aa/rentaura
  branch: main
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: "products"
    label: "Products"
    folder: "src/content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "price", label: "Price", widget: "number" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "video", label: "Video", widget: "file", required: false }
      - { name: "body", label: "Details", widget: "markdown" }
